version: '3.8'

services:
  account-service:
    build: ./applications/account-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  transaction-service:
    build: ./applications/transaction-service  
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  notification-service:
    build: ./applications/notification-service
    ports:
      - "3003:3003" 
    environment:
      - NODE_ENV=development
      - APP_VERSION=1.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-frontend:
    build: ./applications/web-frontend
    ports:
      - "3000:80"
    depends_on:
      - account-service
      - transaction-service
      - notification-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: banking-network
